<?php
/**
 * Created by PhpStorm.
 * User: mlecz
 * Date: 16.03.2017
 * Time: 22:20
 */
$pages = $this->pages;
$pageName = null;
foreach ($pages as $p => $pp) {
    $pageName = $pp->getLabel();
}
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><?= $pageName; ?></h2>
        <ol class="breadcrumb">
            <?php foreach ($this->pages as $key => $page): ?>
                <?php if ($key < count($this->pages) - 1): ?>
                    <li>
                        <a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
                    </li>
                    <?php else: ?>
                    <li class="actve">
                        <strong><?= $page->getLabel() ?></strong>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
