<?php
/**
 * User: mlecz
 * Date: 31.01.2017
 * Time: 15:55
 */
?>

<div class="row">
    <?php
        $form->prepare();
        echo $this->form()->openTag($form);
        $user = $form->get('email');
    ?>
    <div class="form-group">
    <?php
        echo $this->formLabel($user);
        echo $this->formInput($user);
    ?>
    </div>
    <div class="form-group">
    <?php
        $password = $form->get('password');
        echo $this->formLabel($password);
        echo $this->formInput($password);
    ?>
    </div>
    <?php
        echo $this->formSubmit($form->get('createSubmit'));
    ?>
    <a class="btn btn-block btn-social btn-facebook" href="<?php echo $urlF ?>" style="text-align: center"><span class="fa fa-facebook"></span><?php echo $this->translate("Zaloguj przez Facebook", 'default', LOCALE); ?></a>
    <a class="btn btn-block btn-social btn-google" href="<?php echo $urlG ?>" style="text-align: center"><span class="fa fa-google"></span><?php echo $this->translate("Zaloguj przez Google+", 'default', LOCALE); ?></a>
    <a href="<?php echo $this->url('auth/reset'); ?>"><small><?php echo $this->translate("Zapomniałeś hasła?", 'default', LOCALE); ?></small></a>
    <p class="text-muted text-center"><small><?php echo $this->translate("Nie masz jeszcze konta?", 'default', LOCALE); ?></small></p>
    <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('auth/register') ?>"><?php echo $this->translate("Zarejestruj", 'default', LOCALE); ?></a>
    <?php
        echo $this->form()->closeTag();
    ?>
</div>

<script>
    var response = JSON.parse('<?php echo $this->resp ?>');
    makeToast(response[1], response[0], response[2]);
</script>