<?php
/**
 * User: mlecz
 * Date: 31.01.2017
 * Time: 15:55
 */
?>

<div class="row">
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    $user = $form->get('email');
    echo $this->formLabel($user);
    echo $this->formInput($user);
    $password = $form->get('password');
    echo $this->formLabel($password);
    echo $this->formInput($password);
    echo $this->formSubmit($form->get('createSubmit'));
    echo $this->form()->closeTag();
    ?>

    <a class="btn btn-block btn-social btn-facebook" href="<?php echo $urlF ?>"><span
                class="fa fa-facebook"></span><?php echo $this->translate("Zaloguj przez Facebook", 'default', LOCALE); ?>
    </a>
    <a class="btn btn-block btn-social btn-google" href="<?php echo $urlG ?>"><span
                class="fa fa-google"></span><?php echo $this->translate("Zaloguj przez Google+", 'default', LOCALE); ?>
    </a>
    <a class="btn btn-block btn-danger"
       href="<?php echo $this->url('auth/register', ['locale' => LOCALE]) ?>"><?php echo $this->translate("Zarejestruj", 'default', LOCALE); ?></a>
</div>
