<?php
/**
 * User: mlecz
 * Date: 31.01.2017
 * Time: 10:52
 */

?>
<div class="row">
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    $user = $form->get('email');
    echo $this->formLabel($user);
    echo $this->formInput($user);
    $password = $form->get('password');
    echo $this->formLabel($password);
    echo $this->formInput($password);
    $sPassword = $form->get('spassword');
    echo $this->formLabel($sPassword);
    echo $this->formInput($sPassword);
    $capt = $form->get('capt');
    echo $this->formLabel($capt);
    echo $this->formElement($capt);
    echo $this->formSubmit($form->get('createSubmit'));
    echo $this->form()->closeTag();
    ?>
</div>
<?php
echo '<div id="' . $this->translate('Email użytkownika', 'default', LOCALE) . '">' . $this->formElementErrors($user) . '</div>';
echo '<div id="' . $this->translate('Hasło', 'default', LOCALE) . '">' . $this->formElementErrors($password) . '</div>';
echo '<div id="' . $this->translate('Powtórz hasło', 'default', LOCALE) . '">' . $this->formElementErrors($sPassword) . '</div>';
echo '<div id="' . $this->translate('Potwierdź czy jesteś człowiekiem, wpisując teskt z obrazka.', 'default', LOCALE) . '">' . $this->formElementErrors($capt) . '</div>';
?>
<script>
    $('pre').addClass('cap');
    $('ul').addClass('hidden');
    pushToastMessageForm($('ul'));
</script>


