<?php
/**
 * User: Paweł Mleczko
 * Date: 06.02.2017
 * Time: 22:07
 */
?>

<div class="row">
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    $user = $form->get('email');
    echo $this->formLabel($user);
    echo $this->formInput($user);
    echo $this->formSubmit($form->get('createSubmit'));
    echo $this->form()->closeTag();
    ?>
</div>
<?php
echo '<div id="' . $this->translate('Email użytkownika', 'default', LOCALE) . '">' . $this->formElementErrors($user) . '</div>';
?>
<script>
    $('ul').addClass('hidden');
    pushToastMessageForm($('ul'));
</script>

