<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 11.09.17
 * Time: 15:01
 */
?>
<div class="col-lg-12">
    <div id="ibox" class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Dodaj pokój</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content" style="min-height: 200px">
            <div class="form-group">
                <?php $roomForm->prepare(); ?>
                <?= $this->form()->openTag($roomForm); ?>
                <?= $this->formRow($roomForm->get('name')); ?>
                <?= $this->formRow($roomForm->get('type')); ?>
                <?= $this->formSubmit($roomForm->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
