<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 11.09.17
 * Time: 13:41
 */
?>
<div class="col-lg-12">
    <div id="ibox" class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Wszystkie pokoje</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content" style="min-height: 200px">
            <table id="room-list" class="table table-striped table-hover" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nazwa</th>
                        <th>Typ</th>
                        <th>Data dodania</th>
                        <th>Data edycji</th>
                        <th>Wolny</th>
                        <th>Akcja</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Nazwa</th>
                        <th>Typ</th>
                        <th>Data dodania</th>
                        <th>Data edycji</th>
                        <th>Wolny</th>
                        <th>Akcja</th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php foreach ($rooms as $room): ?>
                        <tr>
                            <td><?= $room->getId() ?></td>
                            <td><?= $room->getName() ?></td>
                            <td><?= $room->getType() ?></td>
                            <td><?= $room->getDateAdd()->format('d.m.Y H:i') ?></td>
                            <td><?= $room->getDateEdit() ? $room->getDateEdit()->format('d.m.Y H:i') : '' ?></td>
                            <td><?= $room->isFree() ? 'TAK' : 'NIE' ?></td>
                            <td>asd</td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#room-list').DataTable();
    });
</script>
