<?= $this->doctype() ?>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INSPINIA | Main view</title>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?php $this->FlashMsg(); ?>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('inspinia/css/style.css'))
        ->prependStylesheet($this->basePath('inspinia/css/animate.css'))
        ->prependStylesheet($this->basePath('inspinia/font-awesome/css/font-awesome.css'))
        ->prependStylesheet($this->basePath('inspinia/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('inspinia/js/plugins/toastr/toastr.min.js'))
        ->prependFile($this->basePath('inspinia/js/plugins/pace/pace.min.js'))
        ->prependFile($this->basePath('inspinia/js/inspinia.js'))
        ->prependFile($this->basePath('inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('inspinia/js/plugins/metisMenu/jquery.metisMenu.js'))
        ->prependFile($this->basePath('inspinia/js/bootstrap.min.js'))
        ->prependFile($this->basePath('inspinia/js/jquery-3.1.1.min.js'))
    ?>
</head>
<body style="background-color: white;color: black">
<?= $this->content ?>
<?= $this->inlineScript() ?>
</body>
</html>
